import Navbar from '@/components/Navbar'
import './globals.css'
import Footer from '@/components/Footer'
import localfont from 'next/font/local'

const sf = localfont ({
  src: [
    {
      path: "../public/font/SFPRODISPLAYBOLD.ttf",
      weight: "700"
    },
    {
      path: "../public/font/SFPRODISPLAYREGULAR.ttf",
      weight: "400"
    },
    {
      path: "../public/font/SFPRODISPLAYMEDIUM.ttf",
      weight: "500"
    },
  ],
  variable: "--font-sf",
});


export const metadata = {
  title: 'Leumax Technology',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${sf.variable}`}>
      <body className=" min-h-screen text-black-10"> 
        <Navbar />
        <main className=' relative top-[70px]'>
        {children}
        <Footer />
        </main>
        
      </body>
    </html>
  )
}
